# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd361c9a9b60f8f1165078f96a5df7f9ceed5d6a872aa7811206838fb7a08f058c103f825d7ad6b54c0bfee50e8266e723afd32219655b4e2145bbdf77015fb2

test:
  secret_key_base: 67a951de9b1619c248d65e439c1e622cb3fec2256222af1410940610d7922927d3ff18ac01d25995846e0a5f5ef8516fb7dc16611f9673b37bc5dd6a2aec76d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
